import "@/styles/scss/_base.scss";
import type { AppProps } from "next/app";
import Layout from "../components/layout/layout";
import Head from "next/head";
import { WebShopProvider } from "@/context/context";
import { store } from "@/store/store";
import { Provider } from "react-redux";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <WebShopProvider>
        <Layout>
          <Head>
            <title>Webshop</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1.0"
            />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
              rel="preconnect"
              href="https://fonts.gstatic.com"
              crossOrigin=""
            />
            <link
              href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"
              rel="stylesheet"
            />
          </Head>

          <Component {...pageProps} />
        </Layout>
      </WebShopProvider>
    </Provider>
  );
}
